### PR TITLE
Update gitignore for better coverage

### PR DESCRIPTION
**Pull request by itsarbit**
A small tweak for gitignore for better coverage on different environment.

### CODE REVIEW

**Comment by cychiang** [comment]
Nice! It would be good to include `.idea` also. It's for JetBrains Goland.

**Comment by itsarbit** [comment]
Thanks @cychiang . I am not familiar with `.idea`, but updated.

**Comment by PichuChen** [comment]
LGTM

**Review by PichuChen — APPROVED** [review]

**Comment by itsarbit** [comment]
LGTM

**Comment by FATESAIKOU** [comment]
LGTM

**Pull request merged**
